---
- name: Get software for apt repository management.
  apt: "name={{ item }} state=present"
  with_items:
    - python-apt
    - python-pycurl

- name: Install common dependencies.
  apt: "name={{ item }} state=present"
  with_items:
    - git
    - curl
    - sendmail

- name: Disable the firewall (since this is for local dev only).
  service: name=ufw state=stopped

- name: Download Composer installer.
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-installer.php
    mode: 0755

- name: Run Composer installer.
  command: >
    php composer-installer.php
    chdir=/tmp
    creates=/usr/local/bin/composer

- name: Move Composer into globally-accessible location.
  shell: >
    mv /tmp/composer.phar /usr/local/bin/composer
    creates=/usr/local/bin/composer